### ISSUE TITLE
Create ethertype for RoCE

### ISSUE THREAD

**Issue by Kamalheib** [SoftRoCE/rxe-dev#10]
Need to create new ethertype for RoCE "ETH_P_ROCE"under "include/uapi/linux/if_ether.h" and change the code to use the new ethertype instead of using "ETH_P_RXE" ethertype.

**Comment by psebexen** [comment]
I added the appropriate line to the if_ether.h file according to the hex value from http://standards.ieee.org/develop/regauth/ethertype/eth.txt and updated the constant names in rxe_net. These changes are in a new branch, iss10, commit 9aad10d69517f11390756ee6e9c668198fe93d8d. What else should be addressed as part of this issue? For example, I saw in-comment references to netfilter values which should probably be set in a similar manner.

**Comment by Kamalheib** [comment]
Hi Paul,

Thanks for you update, Related to the ETH_P_ROCE ethertype after we will add support for RoCEv2 I don't think that we will use this ethertype, so i think that no need for this change (i think that we already discussed this issue in our weekly meetings), and you can close this issue.

Related to the other comment you saw in the code could you please open new issues describing this issues so we can discuss each one separately.

Thanks,
Kamal
