### ISSUE TITLE
Netfilter definitions for RoCE

### ISSUE THREAD

**Issue by psebexen** [SoftRoCE/rxe-dev#26]
Similar to Issue #10, rxe_net.h contains macro-defined constants for `NFPROTO_RXE`, commented to be defined in .../include/linux/netfilter.h, and `NF_RXE_IN` and `NF_RXE_OUT`, commented to be defined in .../include/linux/netfilter_rxe.h.

**Comment by Kamalheib** [comment]
No need for all NF\* defines after we add RoCEv2 support because we aren't going to use NF_HOOK functions.

So i'm closing this issue.
