### ISSUE TITLE
Multicast doesn't work

### ISSUE THREAD

**Issue by Kamalheib** [SoftRoCE/rxe-dev#31]
Need to check multicast traffic after RoCEv2 to see if it's not affected.

**Comment by vtrocelab** [comment]
Kamal, did you check it again? It seems multicast occasionally works in our lab. Leon

**Comment by wentianxiaokai** [comment]
Hello,Could you tell me how to test multicast ? Or how to check multicast traffic after RoCEv2 to see if it's not affected?
I run "mckey -m 192.168.3.146" on server whose ip address is 192.168.3.142.And then I run "mckey -m 192.168.3.142 -s" on the client whose ip address is 192.168.3.146. And  the client send data and stop normall.But the server got noting received.
Can you tell me how to deal with it?
Thanks a lot.
