### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by tiredbrit** [SoftRoCE/rxe-dev#42]
when I do the make for librxe-dev I get:
src/rxe.c:61:25: fatal error:  rdma/ib_rxe.h: No such file or directory
# include <rdma/ib_rxe.h>

using CentOS 7, 4.0.0

**Comment by psebexen** [comment]
Is it safe to assume your 4.0.0 kernel was built and installed from this repository's source by a procedure similar to that described on the wiki - https://github.com/SoftRoCE/rxe-dev/wiki/rxe-dev:-Home?

If so, please try to run the following additional step from your kernel tree top-level directory:

```
make headers_install INSTALL_HDR_PATH=/usr
```

It looks like I may have omitted this step from the directions unintentionally; we should add it if this does solve this issue.

**Comment by tiredbrit** [comment]
Yes, those are the instructions that I followed. Doing the make headers_install did the trick. Thanks.

**Comment by psebexen** [comment]
Great, I will go ahead and add that step to the instructions and close this issue. Thank you for pointing that out.
