### ISSUE TITLE
No rdma_rxe

### ISSUE THREAD

**Issue by Peng-git-hub** [SoftRoCE/rxe-dev#57]
After  compiling and installing the kernel,i can't find the moudle of rdma_rxe(rdma_rxe.ko).
I was following the instructions and during the building there was no error .

qipeng@qipeng-OptiPlex-380:/boot/grub$ modinfo rdma_rxe
modinfo: ERROR: Module rdma_rxe not found
but there is ib_rxe:
filename:       /lib/modules/4.0.0+/kernel/drivers/infiniband/hw/rxe/ib_rxe.ko

**Comment by arvindkini** [comment]
Can you please share what was the problem here ? I wonder if the module got renamed to ib_rxe from rdma_rxe. Was that it ? 
Thank you.
Arvind
