### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by jdbyzfhy** [SoftRoCE/rxe-dev#58]
I install SoftRoCE successfully,but it couldn't work when I connected the server and client 
![2016-11-23 17-16-16](https://cloud.githubusercontent.com/assets/20415201/20584611/5306c044-b22f-11e6-8778-f2c511dde0ef.png)
![2016-11-23 17-18-06](https://cloud.githubusercontent.com/assets/20415201/20584613/589a03ea-b22f-11e6-8136-bb0b20275f74.png)

**Comment by thinkl3** [comment]
how did u solve it,i met the same problem as yours ,can u share the way to solve it? 

thx!
